AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to enable default Lake Formation tags, permissions, and audit logging.


Parameters:
  ProviderName: 
    Type: String
    Description: Provider name of the Service Catalog portfolio
    MinLength: 3
    MaxLength: 63
    AllowedPattern: '^[a-zA-Z0-9.-]+$'
    ConstraintDescription: "must be an alphanumeric string with hyphens and periods, between 3 and 63 characters."
    Default: Cloud2

  AdminRole:
    Type: String
    Description: Role that has admin access to the portfolio.
    Default: 'arn:aws:iam::907826444281:role/aws-reserved/sso.amazonaws.com/eu-west-1/AWSReservedSSO_AWSAdministratorAccess_0c86b59f2b52e989'
  
  ReadOnlyRole:
    Type: String
    Description: Role that has read-only access to the portfolio.
    Default: 'arn:aws:iam::907826444281:role/aws-reserved/sso.amazonaws.com/eu-west-1/AWSReservedSSO_AWSReadOnlyAccess_825469f2680a35bc'

Conditions:
  HasAdminRole: !Not [ !Equals [ !Ref AdminRole, "" ] ]
  HasReadOnlyRole: !Not [ !Equals [ !Ref ReadOnlyRole, "" ] ]

Resources:
  LFTagCanRead:
    Type: AWS::LakeFormation::Tag
    Properties:
      TagKey: CanRead
      TagValues: 
        - Enduser
        - BIAdmin
        - Payroll

  LFTagCanAdmin:
    Type: AWS::LakeFormation::Tag
    Properties:
      TagKey: CanAdmin
      TagValues: 
        - Enduser
        - BIAdmin
        - Payroll

  LFTagQSVisible:
    Type: AWS::LakeFormation::Tag
    Properties:
      TagKey: QSVisible
      TagValues: 
        - false
        - true

  AuditLogBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::AccountId}-data-audit-logs'
      VersioningConfiguration:
        Status: Enabled

  DataBrewServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DataBrewServiceRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: databrew.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueDataBrewServiceRole
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  GlueServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GlueServiceRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  DataManagementPortfolio:
    Type: AWS::ServiceCatalog::Portfolio
    Properties:
      DisplayName: DataManagement
      ProviderName: !Ref ProviderName
      Description: Portfolio for managing data services

  PortfolioAdminAssociation:
    Type: AWS::ServiceCatalog::PortfolioPrincipalAssociation
    Condition: HasAdminRole
    Properties:
      PortfolioId: !Ref DataManagementPortfolio
      PrincipalARN: !Ref AdminRole
      PrincipalType: IAM

  PortfolioReadOnlyAssociation:
    Type: AWS::ServiceCatalog::PortfolioPrincipalAssociation
    Condition: HasReadOnlyRole
    Properties:
      PortfolioId: !Ref DataManagementPortfolio
      PrincipalARN: !Ref ReadOnlyRole
      PrincipalType: IAM