AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to enable default Lake Formation tags, permissions, and audit logging.


Parameters:
  Owner: 
    Type: String
    Description: Owner of the Service Catalog portfolio
    MinLength: 3
    MaxLength: 63
    AllowedPattern: '^[a-z0-9.-]+$'
    ConstraintDescription: "must be a lowercase alphanumeric string with hyphens and periods, between 3 and 63 characters."

  ProviderName: 
    Type: String
    Description: Provider name of the Service Catalog portfolio
    MinLength: 3
    MaxLength: 63
    AllowedPattern: '^[a-z0-9.-]+$'
    ConstraintDescription: "must be a lowercase alphanumeric string with hyphens and periods, between 3 and 63 characters."
    Default: Cloud2

  UserRoles:
    Type: List<String>
    Description: List of roles that need access to the portfolio.
    AllowedValues:
      - 'arn:aws:iam::907826444281:role/aws-reserved/sso.amazonaws.com/eu-west-1/AWSReservedSSO_AWSAdministratorAccess_0c86b59f2b52e989'
      - 'arn:aws:iam::907826444281:role/aws-reserved/sso.amazonaws.com/eu-west-1/AWSReservedSSO_AWSReadOnlyAccess_825469f2680a35bc'

Resources:
  LFTagCanRead:
    Type: AWS::LakeFormation::Tag
    Properties:
      TagKey: CanRead
      TagValues: 
        - Enduser
        - BIAdmin
        - Payroll

  LFTagCanAdmin:
    Type: AWS::LakeFormation::Tag
    Properties:
      TagKey: CanAdmin
      TagValues: 
        - Enduser
        - BIAdmin
        - Payroll

  LFTagQSVisible:
    Type: AWS::LakeFormation::Tag
    Properties:
      TagKey: QSVisible
      TagValues: 
        - false
        - true

  AuditLogBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::AccountId}-data-audit-logs'
      VersioningConfiguration:
        Status: Enabled

  DataBrewServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DataBrewServiceRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: databrew.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueDataBrewServiceRole
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  GlueServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GlueServiceRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  DataManagementPortfolio:
    Type: AWS::ServiceCatalog::Portfolio
    Properties:
      DisplayName: DataManagement
      ProviderName: !Ref ProviderName
      Owner: !Ref Owner
      Description: Portfolio for managing data services

  PortfolioUserRoleAssociations:
    Type: AWS::ServiceCatalog::PortfolioPrincipalAssociation
    Properties:
      PortfolioId: !Ref DataManagementPortfolio
      PrincipalARN: !Ref UserRoles
      PrincipalType: IAM