AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an S3 bucket location with specified access permissions.

Parameters:

  AccessRole:
    Type: String
    Description: Role that has access to the location.
    AllowedValues:
      - 'BIAdmin'
      - 'Payroll'
    Default: 'BIAdmin'

  Prefix:
    Type: String
    Default: data
    Description: Prefix for the location
    MinLength: 3
    MaxLength: 63
    AllowedPattern: '^[a-z0-9.-]+$'
    ConstraintDescription: "must be a lowercase alphanumeric string with hyphens and periods, between 3 and 63 characters."
      
  LocationName:
    Type: String
    Description: Name of the the location.
    MinLength: 3
    MaxLength: 63
    AllowedPattern: '^[a-z0-9.-]+$'
    ConstraintDescription: "must be a lowercase alphanumeric string with hyphens and periods, between 3 and 63 characters."

Mappings:
  RoleNameToRoleArn:
    BIAdmin:
      Arn: 'arn:aws:iam::907826444281:role/aws-reserved/sso.amazonaws.com/eu-west-1/AWSReservedSSO_AWSAdministratorAccess_0c86b59f2b52e989'
    Payroll:
      Arn: 'arn:aws:iam::907826444281:role/aws-reserved/sso.amazonaws.com/eu-west-1/AWSReservedSSO_AWSReadOnlyAccess_825469f2680a35bc'
    DataBrewServiceRole:
      Arn: 'arn:aws:iam::907826444281:role/DataBrewServiceRole'
    GlueServiceRole:
      Arn: 'arn:aws:iam::907826444281:role/GlueServiceRole'

Resources:
  LocationBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${Prefix}-${LocationName}-${AWS::AccountId}'
      AccessControl: Private

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LocationBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AccessRolePolicy
            Effect: Allow
            Principal:
              AWS: !FindInMap [ RoleNameToRoleArn, !Ref AccessRole, Arn ]
            Action:
              - 's3:*'
            Resource:
              - !GetAtt LocationBucket.Arn
              - !Sub '${LocationBucket.Arn}/*'
          - Sid: DataBrewServiceRoleAccess
            Effect: Allow
            Principal:
              AWS: !FindInMap [ RoleNameToRoleArn, DataBrewServiceRole, Arn ]
            Action:
              - 's3:*'
            Resource:
              - !GetAtt LocationBucket.Arn
              - !Sub '${LocationBucket.Arn}/*'
          - Sid: GlueServiceRoleAccess
            Effect: Allow
            Principal:
              AWS: !FindInMap [ RoleNameToRoleArn, GlueServiceRole, Arn ]
            Action:
              - 's3:*'
            Resource:
              - !GetAtt LocationBucket.Arn
              - !Sub '${LocationBucket.Arn}/*'

