AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an S3 bucket location with specified access permissions.

Parameters:

  AdminRole:
    Type: String
    Description: Role that has admin access to the location.
    Default: 'arn:aws:iam::907826444281:role/aws-reserved/sso.amazonaws.com/eu-west-1/AWSReservedSSO_AWSAdministratorAccess_0c86b59f2b52e989'
  
  ReadOnlyRole:
    Type: String
    Description: Role that has read-only access to the location.
    Default: 'arn:aws:iam::907826444281:role/aws-reserved/sso.amazonaws.com/eu-west-1/AWSReservedSSO_AWSReadOnlyAccess_825469f2680a35bc'

  DataBrewServiceRole:
    Type: String
    Description: Role that has access to AWS DataBrew.
    Default: 'arn:aws:iam::907826444281:role/DataBrewServiceRole'

  GlueServiceRole:
    Type: String
    Description: Role that has access to AWS Glue.
    Default: 'arn:aws:iam::907826444281:role/GlueServiceRole'

  Prefix:
    Type: String
    Default: data
    Description: Prefix for the location
    MinLength: 3
    MaxLength: 63
    AllowedPattern: '^[a-z0-9.-]+$'
    ConstraintDescription: "must be a lowercase alphanumeric string with hyphens and periods, between 3 and 63 characters."
      
  LocationName:
    Type: String
    Description: Name of the the location.
    MinLength: 3
    MaxLength: 63
    AllowedPattern: '^[a-z0-9.-]+$'
    ConstraintDescription: "must be a lowercase alphanumeric string with hyphens and periods, between 3 and 63 characters."

Conditions:
  HasAdminRole: !Not [ !Equals [ !Ref AdminRole, "" ] ]
  HasReadOnlyRole: !Not [ !Equals [ !Ref ReadOnlyRole, "" ] ]
  HasDataBrewServiceRole: !Not [ !Equals [ !Ref DataBrewServiceRole, "" ] ]
  HasGlueServiceRole: !Not [ !Equals [ !Ref GlueServiceRole, "" ] ]

Resources:
  LocationBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${Prefix}-${LocationName}-${AWS::AccountId}'
      AccessControl: Private

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LocationBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AdminRoleAccess
            Effect: Allow
            Principal:
              AWS: !If [ HasAdminRole, !Ref AdminRole, !Ref "AWS::NoValue" ]
            Action:
              - 's3:*'
            Resource:
              - !GetAtt LocationBucket.Arn
              - !Sub '${LocationBucket.Arn}/*'
          - Sid: ReadOnlyRoleAccess
            Effect: Allow
            Principal:
              AWS: !If [ HasReadOnlyRole, !Ref ReadOnlyRole, !Ref "AWS::NoValue" ]
            Action:
              - 's3:*'
            Resource:
              - !GetAtt LocationBucket.Arn
              - !Sub '${LocationBucket.Arn}/*'
          - Sid: DataBrewServiceRoleAccess
            Effect: Allow
            Principal:
              AWS: !If [ HasDataBrewServiceRole, !Ref DataBrewServiceRole, !Ref "AWS::NoValue" ]
            Action:
              - 's3:*'
            Resource:
              - !GetAtt LocationBucket.Arn
              - !Sub '${LocationBucket.Arn}/*'
          - Sid: GlueServiceRoleAccess
            Effect: Allow
            Principal:
              AWS: !If [ HasGlueServiceRole, !Ref GlueServiceRole, !Ref "AWS::NoValue" ]
            Action:
              - 's3:*'
            Resource:
              - !GetAtt LocationBucket.Arn
              - !Sub '${LocationBucket.Arn}/*'

